name: Build Windows Wheel

on:
  push:
    branches: ["c_wrapper_winwheel"]
  pull_request:

jobs:
  build-windows-wheel:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: "x64"

      - name: Install MSYS2 + gfortran
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: mingw-w64-x86_64-gcc-fortran

      - name: Add MSYS2 to PATH
        run: |
          echo "C:\msys64\mingw64\bin" >> $env:GITHUB_PATH

      - name: Install cibuildwheel
        shell: bash
        run: |
          python -m pip install cibuildwheel
          pip install -r requirements.txt

      - name: Build wheels
        shell: bash
        run: cibuildwheel --platform windows --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp313-*"
          CIBW_ARCHS: "AMD64"
          FC: gfortran
          CC: gcc
          CXX: g++

      - name: Clean wheel and remove *.dll.a
        shell: bash
        run: |
          unzip wheelhouse/*.whl -d wheel_tmp
          rm -f wheel_tmp/cm4/*.dll.a

      - name: Repack cleaned wheel
        shell: pwsh
        run: |
          mkdir -p cleaned
          $wheel = Get-ChildItem wheelhouse\*.whl | Select-Object -ExpandProperty Name
          Compress-Archive -Path wheel_tmp\* -DestinationPath "cleaned\$wheel"

      - name: Run delvewheel repair
        shell: bash
        run: |
          delvewheel repair cleaned/*.whl --no-mangle cm4.cm4field_arr --wheel-dir wheelhouse
          
          

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: windows-wheels
          path: wheelhouse/*.whl

  test_artifacts:
    name: Test Artifacts
    runs-on: windows-latest
    needs: build-windows-wheel

    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.13"
            architecture: "x64"

        - name: Download Artifacts
          uses: actions/download-artifact@v4
          with:
            name: windows-wheels
            path: wheelhouse

        - name: Create virtual environment
          run: python -m venv venv

        - name: Install the wheel
          shell: pwsh
          run: |
            .\venv\Scripts\Activate.ps1
            python -m pip install --upgrade pip
            pip install (Get-Item wheelhouse\*.whl)
            unzip -l (Get-Item wheelhouse\*.whl).FullName

        - name: Run smoke test
          shell: pwsh
          run: |
            cd $env:GITHUB_WORKSPACE
            .\venv\Scripts\Activate.ps1
            python -c "import cm4; print(cm4.__version__)"
            python example.py
