name: Build Mac Wheel for CM4

on:
  push:
    branches: ["c_wrapper_winwheel"]

jobs:
  build-mac-wheel:
    runs-on: macos-latest


    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Build universal2 wheels
        uses: pypa/cibuildwheel@v3.0.1
        env:
            CIBW_ARCHS: x86_64 arm64
            CIBW_PLATFORM: macos
            CIBW_SKIP: "*-musllinux*"

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
            name: macos-universal2-wheels
            path: wheelhouse/*.whl


