name: Build Mac Wheel for CM4

on:
  push:
    branches: ["xc_wrapper_winwheel"]

jobs:
  build-mac-x86_64_wheel:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["macos-13", "macos-latest"]
        python-version: [ "3.9", "3.10", "3.11", "3.12", "3.13" ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install gfortran
        run: |
          brew install gfortran
          which gfortran


      - name: Build and install cm4
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m build --wheel 

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: macos-wheels-${{ matrix.os }}-${{ matrix.python-version }}
          path: dist/*.whl


