name: c_wrapper ci/cd

on:
  push:
    branches: ["linux-compile"]  # Assign the branch that triggers this workflow

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [ '3.13']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python_version }}

    - name: Build and install cm4field
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m build --wheel 
        pip install dist/*.whl

    - name: Run fortran python parity test
      run: |
            python tests/fortran_python_parity_test.py

    - name: Run upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: fortran_python_parity_results.zip
        path: tests/results/*
        
    
