name: test_pyversion ci/cd

on:
  push:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [ '3.9', '3.10', '3.11', '3.12']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python_version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install meson
        pip install .

    - name: Run smoke test
      run: |
        python example.py

    - name: Run Unit Tests
      run: |
        python tests/test_ext.py
        python tests/test_arr_calc.py
        
    
