name: Build Windows Wheel

on:
  push:
    branches: ["c_wrapper_winwheel"] # Assign the branch that triggers this workflow

jobs:
  release-windows-wheel:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: "x64"

      - name: Install MSYS2 + gfortran
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: mingw-w64-x86_64-gcc-fortran

      - name: Add MSYS2 to PATH
        run: |
          echo "C:\msys64\mingw64\bin" >> $env:GITHUB_PATH

      - name: Install dependencies and cibuildwheel
        shell: bash
        run: |
          python -m pip install cibuildwheel
          pip install -r requirements.txt

      - name: Build wheels
        shell: bash
        env:
          CIBW_ARCHS: "AMD64"
          CIBW_SKIP: "cp314t-* cp314-* pp314-*"
          FC: gfortran
          CC: gcc
          CXX: g++
        run: |
          cibuildwheel --platform windows --print-build-identifiers
          cibuildwheel --platform windows --output-dir wheelhouse


      - name: Repack cleaned wheel
        shell: pwsh
        run: |
          mkdir -p cleaned
          $wheels = Get-ChildItem -Path "wheelhouse" -File
          
          foreach ($wheel in $wheels){
              $name = [IO.Path]::GetFileNameWithoutExtension($wheel.Name)
              Expand-Archive -Path $wheel.FullName -DestinationPath "tmp_${name}" -Force
              Remove-Item -Path "tmp_${name}\cm4\*.dll.a" -Force
              Compress-Archive -Path "tmp_${name}\*" -DestinationPath "cleaned\$($wheel.Name)" -Force
          }
         

      - name: Run delvewheel repair
        shell: bash
        run: |
          for file in cleaned/*.whl; do
            delvewheel repair "$file" --no-mangle cm4.cm4field_arr --wheel-dir wheelhouse
          done

      - name: Upload cleaned wheels
        uses: softprops/action-gh-release@v1
        with:
            draft: false
            files: wheelhouse/*.whl
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}