name: Build Windows Wheel

on:
  push:
    branches: ["python314"] # Assign the branch that triggers this workflow

jobs:
  build-windows-wheel:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.14"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: "x64"

      - name: Install MSYS2 + gfortran
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: mingw-w64-x86_64-gcc-fortran

      - name: Add MSYS2 to PATH
        run: |
          echo "C:\msys64\mingw64\bin" >> $env:GITHUB_PATH

      - name: Install dependencies and cibuildwheel # Upgrade to >=3.1.0 after Python3.14 final release
        shell: bash
        run: |
          python -m pip install cibuildwheel==3.1.0 delvewheel
          pip install -r requirements.txt

      - name: Build wheels
        shell: bash
        run: cibuildwheel --platform windows --output-dir wheelhouse
        env:
          CIBW_ARCHS: "AMD64"
          FC: gfortran
          CC: gcc
          CXX: g++
          CIBW_BUILD: "cp311-* cp312-* cp313-* cp314-*"
          CIBW_TEST_REQUIRES: "numpy"
          CIBW_TEST_COMMAND: "python -c \"import cm4; print(cm4.__version__)\" && python {project}/tests/fortran_python_parity_test.py"
          CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: "delvewheel repair --add-path C:\\\\msys64\\\\mingw64\\\\bin -w {dest_dir} {wheel}"

      - name: Repack cleaned wheel
        shell: pwsh
        run: |
          mkdir -p cleaned
          $wheels = Get-ChildItem -Path "wheelhouse" -File
          
          foreach ($wheel in $wheels){
              $name = [IO.Path]::GetFileNameWithoutExtension($wheel.Name)
              Expand-Archive -Path $wheel.FullName -DestinationPath "tmp_${name}" -Force
              Remove-Item -Path "tmp_${name}\cm4\*.dll.a" -Force
              Compress-Archive -Path "tmp_${name}\*" -DestinationPath "cleaned\$($wheel.Name)" -Force
          }
         :
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: windows-wheels
          path: wheelhouse/*.whl
