name: Test manylinux 2_28 Wheel

on:
  push:
    branches: ["parallize_cicd"] # Assign the branch that triggers this workflow

jobs:
  build-wheel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["cp311", "cp312", "cp313", "cp314"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          version: latest


      - name: Build wheels with cibuildwheel # Upgrade to >=3.1.0 after Python3.14 final release
        uses: pypa/cibuildwheel@v3.4.0
        env:
          CIBW_ARCHS: "x86_64"
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
          CIBW_BUILD_FRONTEND: "build[uv]"
          # Skip to build musllinux and 32-bit manylinux wheels
          CIBW_SKIP: "*-musllinux* *-manylinux_i686"
          CIBW_BUILD: "${{ matrix.python-version }}-*"
          CIBW_TEST_COMMAND: "python -c \"import cm4; print(cm4.__version__)\" && python {project}/tests/fortran_python_parity_test.py"

      - name: Release wheels to Github Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: wheelhouse/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}