name: Build CM4 wheels in macOS

on:
  push:
    branches: [vendor_gfortran_into_wheel]

jobs:
  build-mac-wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "macos-latest" ]
        python-version: [ "cp313"]
        include:
          - os: "macos-latest"
            arch: "arm64"
          #- os: "macos-15-intel"
          #  arch: "x86_64"

    steps:
      - uses: actions/checkout@v3

      - name: Install Fortran compiler
        run: |
            brew update
            brew install gcc
            echo "$(brew --prefix)/bin" >> "$GITHUB_PATH"
            echo "FC=$(brew --prefix)/bin/gfortran" >> "$GITHUB_ENV"
            gfortran --version

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.4.0
        env:
          CIBW_BUILD: "${{ matrix.python-version }}-*"
          CIBW_ARCHS_MACOS: "${{ matrix.arch }}"
          MACOSX_DEPLOYMENT_TARGET: "14.0"
          CIBW_BEFORE_BUILD_MACOS: "python -m pip install delocate"
          CIBW_REPAIR_WHEEL_COMMAND_MACOS: "delocate-wheel --require-archs {delocate_archs} -w {dest_dir} -v {wheel}"
          CIBW_TEST_COMMAND: "python -c \"import cm4; print(cm4.__version__)\" && python {project}/tests/fortran_python_parity_test.py"

      - name: Test the built wheel
        run: |
          pip install wheelhouse/*.whl
          python -c "import cm4; print(cm4.__version__)"
