name: Test the path for uploading wheels to github release

on:
  push:
    branches: ["fix_release_path"]

jobs:
  build_linux_wheels:
    runs-on: ubuntu-slim
    strategy:
      matrix:
        python-version: ["cp311", "cp312", "cp313", "cp314"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          version: latest


      - name: Build wheels with cibuildwheel
        uses: pypa/cibuildwheel@v3.4.0
        env:
          CIBW_ARCHS: "x86_64"
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
          CIBW_BUILD_FRONTEND: "build[uv]"
          # Skip to build musllinux and 32-bit manylinux wheels
          CIBW_SKIP: "*-musllinux* *-manylinux_i686"
          CIBW_BUILD: "${{ matrix.python-version }}-*"
          CIBW_TEST_COMMAND: "python -c \"import cm4; print(cm4.__version__)\" && python {project}/tests/fortran_python_parity_test.py"

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.python-version }}


  build-mac-wheel:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "macos-latest"]
        python-version: [ "3.11", "3.12", "3.13", "3.14" ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install gfortran
        uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: gcc

      - name: Build and install cm4
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m build --wheel 

      - name: Test the built wheel
        run: |
          pip install dist/*.whl
          python -c "import cm4; print(cm4.__version__)"
          python tests/fortran_python_parity_test.py


      - name: Upload wheels as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-py${{ matrix.python-version }}
          path: dist/*.whl

  release-wheels:
    needs: [build_linux_wheels, build-mac-wheel]
    runs-on: ubuntu-latest

    steps:
      - name: Download built wheels
        uses: actions/download-artifact@v5
        with:
          pattern: wheels-*
          path: dist
          merge-multiple: true

      - name: List Wheels
        run: ls -R dist

      - name: Upload wheels to Github Release
        uses: softprops/action-gh-release@v1

        with:
          draft: true
          files: dist/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
