name: Test Mac Wheel for CM4

on:
  push:
    branches: ["parallize_cicd"] # Assign the branch that triggers this workflow

jobs:
  build-mac-wheel:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: "macos-latest"
            arch: "x86_64"
          - os: "macos-15"
            arch: "x86_64"
        python-version: ["cp311", "cp312", "cp313", "cp314"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          version: latest

      - name: Install gfortran
        uses: fortran-lang/setup-fortran@v1.9.0
        id: setup-fortran
        with:
          compiler: gcc
          version: "15"

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.4.0
        env:
          CIBW_BUILD: "${{ matrix.python-version }}-*"
          CIBW_ARCHS_MACOS: ${{ matrix.arch }}
          # Set the OS floor (11.0 is a safe modern bet for universal2)
          MACOSX_DEPLOYMENT_TARGET: "11.0"
          CIBW_BUILD_FRONTEND: "build[uv]"
          CIBW_TEST_COMMAND: "python -c \"import cm4; print(cm4.__version__)\" && python {project}/tests/fortran_python_parity_test.py"



