name: Build CM4 wheels in Windows

on:
  push:
    branches: [remove_uv]

jobs:
  build-windows-wheels:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [ "cp311", "cp312", "cp313", "cp314" ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install MSYS2 + gfortran
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: mingw-w64-x86_64-gcc-fortran

      - name: Add MSYS2 to PATH
        run: |
          echo "C:\msys64\mingw64\bin" >> $env:GITHUB_PATH

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.4.0
        env:
          CIBW_ARCHS: "AMD64"
          CIBW_BUILD: "${{ matrix.python-version }}-*"
          #CIBW_BEFORE_BUILD_WINDOWS: "python -m pip install delvewheel"
          CIBW_TEST_COMMAND: "python -c \"import cm4; print(cm4.__version__)\""
          #CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: "delvewheel repair --add-path C:\\msys64\\mingw64\\bin -w {dest_dir} {wheel}"
